### ISSUE TITLE
Failsafe GPU initialization

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/clesperantoj_prototype#18]
Asking for  GPU with name "Intel" causes an error in case no Intel GPU is available. In pyclesperanto_prototype it falls back to any other GPU and prints a warning.

[Code](https://github.com/clEsperanto/clesperantoj_prototype/blob/d5624dd4786473fa2793d73abb46da10dca2b574/src/main/java/net/clesperanto/ClesperantoJ.java#L26)

```
C:\Users\haase\.jdks\zulu11.62.17-ca-jdk11.0.18-win_x64\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.2\lib\idea_rt.jar=63954:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.2\bin" -Dfile.encoding=UTF-8 -classpath C:\structure\code\clesperantoj_prototype\target\classes;C:\Users\haase\.m2\repository\net\imagej\imagej\2.1.0\imagej-2.1.0.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-common\0.33.0\imagej-common-0.33.0.jar;C:\Users\haase\.m2\repository\net\imglib2\imglib2\5.10.0\imglib2-5.10.0.jar;C:\Users\haase\.m2\repository\net\imglib2\imglib2-roi\0.10.3\imglib2-roi-0.10.3.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-table\0.6.1\scijava-table-0.6.1.jar;C:\Users\haase\.m2\repository\edu\ucar\udunits\4.3.18\udunits-4.3.18.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-launcher\5.0.3\imagej-launcher-5.0.3.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-notebook\0.7.1\imagej-notebook-0.7.1.jar;C:\Users\haase\.m2\repository\org\apache\commons\commons-text\1.8\commons-text-1.8.jar;C:\Users\haase\.m2\repository\org\knowm\xchart\xchart\3.5.4\xchart-3.5.4.jar;C:\Users\haase\.m2\repository\de\erichseifert\vectorgraphics2d\VectorGraphics2D\0.13\VectorGraphics2D-0.13.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-ops\0.45.5\imagej-ops-0.45.5.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-mesh\0.8.0\imagej-mesh-0.8.0.jar;C:\Users\haase\.m2\repository\net\imglib2\imglib2-algorithm\0.11.2\imglib2-algorithm-0.11.2.jar;C:\Users\haase\.m2\repository\net\imglib2\imglib2-algorithm-fft\0.2.0\imglib2-algorithm-fft-0.2.0.jar;C:\Users\haase\.m2\repository\edu\mines\mines-jtk\20151125\mines-jtk-20151125.jar;C:\Users\haase\.m2\repository\net\imglib2\imglib2-realtransform\3.0.0\imglib2-realtransform-3.0.0.jar;C:\Users\haase\.m2\repository\jitk\jitk-tps\3.0.1\jitk-tps-3.0.1.jar;C:\Users\haase\.m2\repository\com\googlecode\efficient-java-matrix-library\ejml\0.24\ejml-0.24.jar;C:\Users\haase\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\haase\.m2\repository\org\scijava\parsington\2.0.0\parsington-2.0.0.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-search\0.7.0\scijava-search-0.7.0.jar;C:\Users\haase\.m2\repository\org\ocpsoft\prettytime\prettytime\4.0.1.Final\prettytime-4.0.1.Final.jar;C:\Users\haase\.m2\repository\org\scijava\scripting-javascript\0.5.0\scripting-javascript-0.5.0.jar;C:\Users\haase\.m2\repository\org\apache\commons\commons-math3\3.6.1\commons-math3-3.6.1.jar;C:\Users\haase\.m2\repository\org\joml\joml\1.9.25\joml-1.9.25.jar;C:\Users\haase\.m2\repository\org\ojalgo\ojalgo\45.1.1\ojalgo-45.1.1.jar;C:\Users\haase\.m2\repository\gov\nist\math\jama\1.0.3\jama-1.0.3.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-updater\0.10.5\imagej-updater-0.10.5.jar;C:\Users\haase\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;C:\Users\haase\.m2\repository\io\scif\scifio\0.41.0\scifio-0.41.0.jar;C:\Users\haase\.m2\repository\io\scif\scifio-jai-imageio\1.1.1\scifio-jai-imageio-1.1.1.jar;C:\Users\haase\.m2\repository\net\imglib2\imglib2-cache\1.0.0-beta-13\imglib2-cache-1.0.0-beta-13.jar;C:\Users\haase\.m2\repository\com\github\ben-manes\caffeine\caffeine\2.4.0\caffeine-2.4.0.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-common\2.83.3\scijava-common-2.83.3.jar;C:\Users\haase\.m2\repository\org\bushe\eventbus\1.4\eventbus-1.4.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-mesh-io\0.1.2\imagej-mesh-io-0.1.2.jar;C:\Users\haase\.m2\repository\com\google\guava\guava\21.0\guava-21.0.jar;C:\Users\haase\.m2\repository\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\haase\.m2\repository\org\smurn\jply\0.2.0\jply-0.2.0.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-plugins-batch\0.1.1\imagej-plugins-batch-0.1.1.jar;C:\Users\haase\.m2\repository\org\scijava\batch-processor\0.4.1\batch-processor-0.4.1.jar;C:\Users\haase\.m2\repository\commons-io\commons-io\2.7\commons-io-2.7.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-deprecated\0.1.4\imagej-deprecated-0.1.4.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-plugins-commands\0.8.1\imagej-plugins-commands-0.8.1.jar;C:\Users\haase\.m2\repository\com\github\sbridges\object-inspector\object-inspector\0.1\object-inspector-0.1.jar;C:\Users\haase\.m2\repository\net\iharder\base64\2.3.8\base64-2.3.8.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-plugins-tools\0.3.1\imagej-plugins-tools-0.3.1.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-plugins-uploader-ssh\0.3.2\imagej-plugins-uploader-ssh-0.3.2.jar;C:\Users\haase\.m2\repository\com\jcraft\jsch\0.1.55\jsch-0.1.55.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-plugins-uploader-webdav\0.3.2\imagej-plugins-uploader-webdav-0.3.2.jar;C:\Users\haase\.m2\repository\org\apache\jackrabbit\jackrabbit-webdav\2.21.1\jackrabbit-webdav-2.21.1.jar;C:\Users\haase\.m2\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar;C:\Users\haase\.m2\repository\org\apache\httpcomponents\httpclient\4.5.12\httpclient-4.5.12.jar;C:\Users\haase\.m2\repository\commons-codec\commons-codec\1.14\commons-codec-1.14.jar;C:\Users\haase\.m2\repository\org\apache\httpcomponents\httpcore\4.4.13\httpcore-4.4.13.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-scripting\0.8.2\imagej-scripting-0.8.2.jar;C:\Users\haase\.m2\repository\org\scijava\scripting-beanshell\0.3.4\scripting-beanshell-0.3.4.jar;C:\Users\haase\.m2\repository\org\apache-extras\beanshell\bsh\2.0b6\bsh-2.0b6.jar;C:\Users\haase\.m2\repository\org\scijava\scripting-clojure\0.1.6\scripting-clojure-0.1.6.jar;C:\Users\haase\.m2\repository\org\clojure\clojure\1.8.0\clojure-1.8.0.jar;C:\Users\haase\.m2\repository\org\scijava\scripting-groovy\0.3.0\scripting-groovy-0.3.0.jar;C:\Users\haase\.m2\repository\org\codehaus\groovy\groovy\3.0.4\groovy-3.0.4.jar;C:\Users\haase\.m2\repository\org\codehaus\groovy\groovy-dateutil\3.0.4\groovy-dateutil-3.0.4.jar;C:\Users\haase\.m2\repository\org\codehaus\groovy\groovy-json\3.0.4\groovy-json-3.0.4.jar;C:\Users\haase\.m2\repository\org\codehaus\groovy\groovy-swing\3.0.4\groovy-swing-3.0.4.jar;C:\Users\haase\.m2\repository\org\codehaus\groovy\groovy-templates\3.0.4\groovy-templates-3.0.4.jar;C:\Users\haase\.m2\repository\org\codehaus\groovy\groovy-xml\3.0.4\groovy-xml-3.0.4.jar;C:\Users\haase\.m2\repository\org\apache\ivy\ivy\2.4.0\ivy-2.4.0.jar;C:\Users\haase\.m2\repository\org\codehaus\gpars\gpars\1.2.1\gpars-1.2.1.jar;C:\Users\haase\.m2\repository\org\multiverse\multiverse-core\0.7.0\multiverse-core-0.7.0.jar;C:\Users\haase\.m2\repository\org\codehaus\jsr166-mirror\jsr166y\1.7.0\jsr166y-1.7.0.jar;C:\Users\haase\.m2\repository\org\scijava\scripting-java\0.4.1\scripting-java-0.4.1.jar;C:\Users\haase\.m2\repository\org\scijava\minimaven\2.2.2\minimaven-2.2.2.jar;C:\Users\haase\.m2\repository\org\scijava\scripting-jruby\0.3.1\scripting-jruby-0.3.1.jar;C:\Users\haase\.m2\repository\org\jruby\jruby-core\9.1.17.0\jruby-core-9.1.17.0.jar;C:\Users\haase\.m2\repository\com\github\jnr\jnr-netdb\1.1.6\jnr-netdb-1.1.6.jar;C:\Users\haase\.m2\repository\com\github\jnr\jnr-enxio\0.16\jnr-enxio-0.16.jar;C:\Users\haase\.m2\repository\com\github\jnr\jnr-x86asm\1.0.2\jnr-x86asm-1.0.2.jar;C:\Users\haase\.m2\repository\com\github\jnr\jnr-unixsocket\0.17\jnr-unixsocket-0.17.jar;C:\Users\haase\.m2\repository\com\github\jnr\jnr-posix\3.0.44\jnr-posix-3.0.44.jar;C:\Users\haase\.m2\repository\com\github\jnr\jnr-constants\0.9.9\jnr-constants-0.9.9.jar;C:\Users\haase\.m2\repository\com\github\jnr\jffi\1.2.16\jffi-1.2.16.jar;C:\Users\haase\.m2\repository\com\github\jnr\jffi\1.2.16\jffi-1.2.16-native.jar;C:\Users\haase\.m2\repository\org\jruby\joni\joni\2.1.15\joni-2.1.15.jar;C:\Users\haase\.m2\repository\org\jruby\extras\bytelist\1.0.15\bytelist-1.0.15.jar;C:\Users\haase\.m2\repository\org\jruby\jcodings\jcodings\1.0.27\jcodings-1.0.27.jar;C:\Users\haase\.m2\repository\org\jruby\dirgra\0.3\dirgra-0.3.jar;C:\Users\haase\.m2\repository\com\headius\invokebinder\1.10\invokebinder-1.10.jar;C:\Users\haase\.m2\repository\com\headius\options\1.4\options-1.4.jar;C:\Users\haase\.m2\repository\com\headius\unsafe-fences\1.0\unsafe-fences-1.0.jar;C:\Users\haase\.m2\repository\com\jcraft\jzlib\1.1.3\jzlib-1.1.3.jar;C:\Users\haase\.m2\repository\com\martiansoftware\nailgun-server\0.9.1\nailgun-server-0.9.1.jar;C:\Users\haase\.m2\repository\joda-time\joda-time\2.10.6\joda-time-2.10.6.jar;C:\Users\haase\.m2\repository\com\headius\modulator\1.0\modulator-1.0.jar;C:\Users\haase\.m2\repository\org\jruby\jruby-stdlib\9.1.17.0\jruby-stdlib-9.1.17.0.jar;C:\Users\haase\.m2\repository\org\scijava\scripting-jython\1.0.0\scripting-jython-1.0.0.jar;C:\Users\haase\.m2\repository\org\python\jython-slim\2.7.2\jython-slim-2.7.2.jar;C:\Users\haase\.m2\repository\org\antlr\antlr\3.5.2\antlr-3.5.2.jar;C:\Users\haase\.m2\repository\org\antlr\ST4\4.0.8\ST4-4.0.8.jar;C:\Users\haase\.m2\repository\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar;C:\Users\haase\.m2\repository\org\antlr\antlr-runtime\3.5.2\antlr-runtime-3.5.2.jar;C:\Users\haase\.m2\repository\org\apache\commons\commons-compress\1.20\commons-compress-1.20.jar;C:\Users\haase\.m2\repository\org\bouncycastle\bcpkix-jdk15on\1.62\bcpkix-jdk15on-1.62.jar;C:\Users\haase\.m2\repository\org\bouncycastle\bcprov-jdk15on\1.62\bcprov-jdk15on-1.62.jar;C:\Users\haase\.m2\repository\org\ow2\asm\asm\7.1\asm-7.1.jar;C:\Users\haase\.m2\repository\org\ow2\asm\asm-commons\7.1\asm-commons-7.1.jar;C:\Users\haase\.m2\repository\org\ow2\asm\asm-tree\7.1\asm-tree-7.1.jar;C:\Users\haase\.m2\repository\org\ow2\asm\asm-analysis\7.1\asm-analysis-7.1.jar;C:\Users\haase\.m2\repository\org\ow2\asm\asm-util\7.1\asm-util-7.1.jar;C:\Users\haase\.m2\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\haase\.m2\repository\com\ibm\icu\icu4j\59.1\icu4j-59.1.jar;C:\Users\haase\.m2\repository\com\carrotsearch\java-sizeof\0.0.5\java-sizeof-0.0.5.jar;C:\Users\haase\.m2\repository\com\github\jnr\jnr-ffi\2.1.10\jnr-ffi-2.1.10.jar;C:\Users\haase\.m2\repository\com\github\jnr\jnr-a64asm\1.0.0\jnr-a64asm-1.0.0.jar;C:\Users\haase\.m2\repository\jline\jline\2.14.5\jline-2.14.5.jar;C:\Users\haase\.m2\repository\io\netty\netty-buffer\4.1.45.Final\netty-buffer-4.1.45.Final.jar;C:\Users\haase\.m2\repository\io\netty\netty-codec\4.1.45.Final\netty-codec-4.1.45.Final.jar;C:\Users\haase\.m2\repository\io\netty\netty-common\4.1.45.Final\netty-common-4.1.45.Final.jar;C:\Users\haase\.m2\repository\io\netty\netty-handler\4.1.45.Final\netty-handler-4.1.45.Final.jar;C:\Users\haase\.m2\repository\io\netty\netty-resolver\4.1.45.Final\netty-resolver-4.1.45.Final.jar;C:\Users\haase\.m2\repository\io\netty\netty-transport\4.1.45.Final\netty-transport-4.1.45.Final.jar;C:\Users\haase\.m2\repository\org\apache\ant\ant\1.9.7\ant-1.9.7.jar;C:\Users\haase\.m2\repository\org\apache\ant\ant-launcher\1.9.7\ant-launcher-1.9.7.jar;C:\Users\haase\.m2\repository\org\scijava\scripting-renjin\0.2.3\scripting-renjin-0.2.3.jar;C:\Users\haase\.m2\repository\org\renjin\renjin-script-engine\0.8.1906\renjin-script-engine-0.8.1906.jar;C:\Users\haase\.m2\repository\org\renjin\renjin-core\0.8.1906\renjin-core-0.8.1906.jar;C:\Users\haase\.m2\repository\org\apache\commons\commons-math\2.2\commons-math-2.2.jar;C:\Users\haase\.m2\repository\org\renjin\gcc-runtime\0.8.1906\gcc-runtime-0.8.1906.jar;C:\Users\haase\.m2\repository\org\netlib\netlib-java\0.9.3-renjin-patched-2\netlib-java-0.9.3-renjin-patched-2.jar;C:\Users\haase\.m2\repository\org\netlib\lapack\0.8\lapack-0.8.jar;C:\Users\haase\.m2\repository\org\netlib\f2jutil\0.8\f2jutil-0.8.jar;C:\Users\haase\.m2\repository\org\netlib\xerbla\0.8\xerbla-0.8.jar;C:\Users\haase\.m2\repository\org\netlib\blas\0.8\blas-0.8.jar;C:\Users\haase\.m2\repository\org\apache\commons\commons-vfs2\2.0\commons-vfs2-2.0.jar;C:\Users\haase\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\haase\.m2\repository\org\apache\maven\scm\maven-scm-api\1.4\maven-scm-api-1.4.jar;C:\Users\haase\.m2\repository\org\codehaus\plexus\plexus-utils\1.5.6\plexus-utils-1.5.6.jar;C:\Users\haase\.m2\repository\org\apache\maven\scm\maven-scm-provider-svnexe\1.4\maven-scm-provider-svnexe-1.4.jar;C:\Users\haase\.m2\repository\org\apache\maven\scm\maven-scm-provider-svn-commons\1.4\maven-scm-provider-svn-commons-1.4.jar;C:\Users\haase\.m2\repository\regexp\regexp\1.3\regexp-1.3.jar;C:\Users\haase\.m2\repository\edu\emory\mathcs\jtransforms\2.4\jtransforms-2.4.jar;C:\Users\haase\.m2\repository\net\sf\jung\jung-api\2.0.1\jung-api-2.0.1.jar;C:\Users\haase\.m2\repository\net\sourceforge\collections\collections-generic\4.01\collections-generic-4.01.jar;C:\Users\haase\.m2\repository\net\sf\jung\jung-graph-impl\2.0.1\jung-graph-impl-2.0.1.jar;C:\Users\haase\.m2\repository\com\sun\codemodel\codemodel\2.6\codemodel-2.6.jar;C:\Users\haase\.m2\repository\org\renjin\stats\0.8.1906\stats-0.8.1906.jar;C:\Users\haase\.m2\repository\org\renjin\renjin-appl\0.8.1906\renjin-appl-0.8.1906.jar;C:\Users\haase\.m2\repository\org\renjin\renjin-gnur-runtime\0.8.1906\renjin-gnur-runtime-0.8.1906.jar;C:\Users\haase\.m2\repository\org\renjin\methods\0.8.1906\methods-0.8.1906.jar;C:\Users\haase\.m2\repository\org\renjin\datasets\0.8.1906\datasets-0.8.1906.jar;C:\Users\haase\.m2\repository\org\renjin\utils\0.8.1906\utils-0.8.1906.jar;C:\Users\haase\.m2\repository\org\renjin\grDevices\0.8.1906\grDevices-0.8.1906.jar;C:\Users\haase\.m2\repository\org\renjin\graphics\0.8.1906\graphics-0.8.1906.jar;C:\Users\haase\.m2\repository\org\scijava\scripting-scala\0.2.2\scripting-scala-0.2.2.jar;C:\Users\haase\.m2\repository\org\scala-lang\scala-compiler\2.12.1\scala-compiler-2.12.1.jar;C:\Users\haase\.m2\repository\org\scala-lang\scala-library\2.12.1\scala-library-2.12.1.jar;C:\Users\haase\.m2\repository\org\scala-lang\scala-reflect\2.12.1\scala-reflect-2.12.1.jar;C:\Users\haase\.m2\repository\org\scala-lang\modules\scala-xml_2.12\1.0.6\scala-xml_2.12-1.0.6.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-ui-swing\0.23.2\imagej-ui-swing-0.23.2.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-ui-awt\0.1.7\scijava-ui-awt-0.1.7.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-ui-swing\0.13.2\scijava-ui-swing-0.13.2.jar;C:\Users\haase\.m2\repository\org\scijava\swing-checkbox-tree\1.0.2\swing-checkbox-tree-1.0.2.jar;C:\Users\haase\.m2\repository\net\sourceforge\jdatepicker\jdatepicker\1.3.2\jdatepicker-1.3.2.jar;C:\Users\haase\.m2\repository\com\miglayout\miglayout-swing\5.2\miglayout-swing-5.2.jar;C:\Users\haase\.m2\repository\com\miglayout\miglayout-core\5.2\miglayout-core-5.2.jar;C:\Users\haase\.m2\repository\org\jfree\jfreechart\1.5.0\jfreechart-1.5.0.jar;C:\Users\haase\.m2\repository\org\jhotdraw\jhotdraw\7.6.0\jhotdraw-7.6.0.jar;C:\Users\haase\.m2\repository\net\imagej\imagej-ui-awt\0.3.1\imagej-ui-awt-0.3.1.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-io-http\0.2.1\scijava-io-http-0.2.1.jar;C:\Users\haase\.m2\repository\com\squareup\okhttp3\okhttp\4.7.2\okhttp-4.7.2.jar;C:\Users\haase\.m2\repository\com\squareup\okio\okio\2.6.0\okio-2.6.0.jar;C:\Users\haase\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.3.70\kotlin-stdlib-common-1.3.70.jar;C:\Users\haase\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.3.71\kotlin-stdlib-1.3.71.jar;C:\Users\haase\.m2\repository\org\jetbrains\annotations\13.0\annotations-13.0.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-plugins-commands\0.2.3\scijava-plugins-commands-0.2.3.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-plugins-io-table\0.3.0\scijava-plugins-io-table-0.3.0.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-optional\1.0.0\scijava-optional-1.0.0.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-plugins-platforms\0.3.1\scijava-plugins-platforms-0.3.1.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-plugins-text-markdown\0.1.3\scijava-plugins-text-markdown-0.1.3.jar;C:\Users\haase\.m2\repository\org\markdownj\markdownj\0.3.0-1.0.2b4\markdownj-0.3.0-1.0.2b4.jar;C:\Users\haase\.m2\repository\org\scijava\scijava-plugins-text-plain\0.1.3\scijava-plugins-text-plain-0.1.3.jar;C:\Users\haase\.m2\repository\org\apache\commons\commons-lang3\3.10\commons-lang3-3.10.jar;C:\Users\haase\.m2\repository\org\scijava\script-editor\0.5.6\script-editor-0.5.6.jar;C:\Users\haase\.m2\repository\com\fifesoft\rsyntaxtextarea\3.1.1\rsyntaxtextarea-3.1.1.jar;C:\Users\haase\.m2\repository\com\fifesoft\languagesupport\3.1.0\languagesupport-3.1.0.jar;C:\Users\haase\.m2\repository\com\fifesoft\autocomplete\3.1.0\autocomplete-3.1.0.jar;C:\Users\haase\.m2\repository\org\mozilla\rhino\1.7.6\rhino-1.7.6.jar;C:\Users\haase\.m2\repository\org\bytedeco\javacpp\1.5.8\javacpp-1.5.8.jar net.clesperanto.ClesperantoJ
Hello World! Native Java
NVIDIA GeForce RTX 3050 Ti Laptop GPU is available
gfx1035 is available
device currently used is : NVIDIA GeForce RTX 3050 Ti Laptop GPU
Exception in thread "main" java.lang.RuntimeException: Error: Fail to find/allocate device with name 'Intel' of type 'all'
	at net.clesperanto.wrapper.clesperantoj$ProcessorJ.setDevice(Native Method)
	at net.clesperanto.ClesperantoJ.main(ClesperantoJ.java:26)

Process finished with exit code 1

```

**Comment by StRigaud** [comment]
This PR should solve this on the CLIc side:
- https://github.com/clEsperanto/CLIc_prototype/pull/160
