### ISSUE TITLE
Test `TestPullImagePlus` fail at build on MacOS

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/clesperantoj_prototype#68]
I have to use `-DskipTests` when calling maven for the build to pass, other wise getting the following error:

```bash
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.155 s -- in TestPullImagePlus
[DEBUG] #
[DEBUG] # A fatal error has been detected by the Java Runtime Environment:
[DEBUG] #
[DEBUG] #  SIGSEGV (0xb) at pc=0x000000011b821134, pid=39304, tid=28675
[DEBUG] #
[DEBUG] # JRE version: OpenJDK Runtime Environment Zulu21.34+19-CA (21.0.3+9) (build 21.0.3+9-LTS)
[DEBUG] # Java VM: OpenJDK 64-Bit Server VM Zulu21.34+19-CA (21.0.3+9-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
[DEBUG] # Problematic frame:
[DEBUG] # C  [libJCLIc.dylib+0x21134]  cle::Array::~Array()+0xe0
[DEBUG] #
[DEBUG] # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
[DEBUG] #
[DEBUG] # An error report file with more information is saved as:
[DEBUG] # /Users/strigaud/Documents/github/clesperanto/clesperantoj_prototype/hs_err_pid39304.log
[DEBUG] #
[DEBUG] # If you would like to submit a bug report, please visit:
[DEBUG] #   http://www.azul.com/support/
[DEBUG] # The crash happened outside the Java Virtual Machine in native code.
/bin/sh: line 1: 39304 Abort trap: 6           '/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home/bin/java' '-Xmx1024m' '-jar' '/Users/strigaud/Documents/github/clesperanto/clesperantoj_prototype/target/surefire/surefirebooter-20240928161223913_18.jar' '/Users/strigaud/Documents/github/clesperanto/clesperantoj_prototype/target/surefire' '2024-09-28T16-12-23_803-jvmRun1' 'surefire-20240928161223913_16tmp' 'surefire_5-20240928161223913_17tmp'
```

**Comment by StRigaud** [comment]
`TestPullImagePlus` issue seems related to a missing `in = null;` at the end of tests. But that does not really fix the build issue I have:

```bash
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project clesperantoj: 
[ERROR] 
[ERROR] Please refer to /Users/strigaud/Documents/github/clesperanto/clesperantoj_prototype/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] ExecutionException Error occurred in starting fork, check output in log
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException Error occurred in starting fork, check output in log
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:456)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:418)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:297)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1241)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1090)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:910)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
[ERROR]         at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
[ERROR]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: Error occurred in starting fork, check output in log
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:577)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.lambda$null$7(ForkStarter.java:401)
[ERROR]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:1583)
[ERROR] 
[ERROR] -> [Help 1]
```

and a dump log:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=71213, tid=27911
#
# JRE version: OpenJDK Runtime Environment Zulu21.34+19-CA (21.0.3+9) (build 21.0.3+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu21.34+19-CA (21.0.3+9-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# C  0x0000000000000000
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Xmx1024m /Users/strigaud/Documents/github/clesperanto/clesperantoj_prototype/target/surefire/surefirebooter-20240928175514716_6.jar /Users/strigaud/Documents/github/clesperanto/clesperantoj_prototype/target/surefire 2024-09-28T17-55-14_589-jvmRun1 surefire-20240928175514716_4tmp surefire_1-20240928175514716_5tmp

Host: "Mac14,5" arm64, 12 cores, 32G, Darwin 23.6.0, macOS 14.6.1 (23G93)
Time: Sat Sep 28 17:55:15 2024 EEST elapsed time: 0.353070 seconds (0d 0h 0m 0s)

---------------  T H R E A D  ---------------

Current thread (0x00000001262a9e00):  JavaThread "JavaCPP Deallocator" daemon [_thread_in_native, id=27911, stack(0x0000000170414000,0x0000000170617000) (2060K)]

Stack: [0x0000000170414000,0x0000000170617000],  sp=0x0000000170616830,  free space=2058k
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.bytedeco.javacpp.Pointer$NativeDeallocator.deallocate(JJ)V+0
j  org.bytedeco.javacpp.Pointer$NativeDeallocator.deallocate()V+27
j  org.bytedeco.javacpp.Pointer$DeallocatorReference.clear()V+46
j  org.bytedeco.javacpp.Pointer$DeallocatorThread.run()V+11
v  ~StubRoutines::call_stub 0x000000011a6d8140

...
```

This still seems related to memory release or something like that.

However, this does not seems to make any of the local run nor CLIJ3 build and test fail ...

**Comment by StRigaud** [comment]
I silence the tests that fail into a side branch / PR. The issue is related to ImagePlus.

**Comment by carlosuc3m** [comment]
HAving a look at it right now! If not silencing the fail can work as a patch for now!
Is it failing on mac intel or max M? @StRigaud

**Comment by StRigaud** [comment]
Mine is M2, don't know if it plays or not. Don't have access to my Unix right now.

**Comment by StRigaud** [comment]
FYI, It does not fail on my Linux ubuntu ...

**Comment by StRigaud** [comment]
Feed back on this after some exploration.

It seems that the tests run fines if we execute them, but fail when automatically called by `maven-surefire-plugin`. Could be nice to fix this but it is not a blocking issue.
