### ISSUE TITLE
Test `TestAbsolute` fail on MacOS `x84-64`

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/clesperantoj_prototype#79]
wrong value return from the Array, failling the `asserts` statements

Fail on MacOS `x84-64` (with radeon) of @tinevez 
Pass on my Ubuntu and MacOS `M2 sillicon`

**Comment by haesleinhuepf** [comment]
Can you please copy the exact error message?

**Comment by StRigaud** [comment]
@tinevez when you have 5 min, can you reproduce this?

**Comment by tinevez** [comment]
```junit
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestAbsolute
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.939 s <<< FAILURE! -- in TestAbsolute
[ERROR] TestAbsolute.testAbsolute -- Time elapsed: 0.909 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1> but was: <131077>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
	at TestAbsolute.testAbsolute(TestAbsolute.java:28)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.ArrayList.forEach(ArrayList.java:1257)

[ERROR] TestAbsolute.testAbsolute1 -- Time elapsed: 0.008 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1> but was: <1299282432>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
	at TestAbsolute.testAbsolute1(TestAbsolute.java:45)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.ArrayList.forEach(ArrayList.java:1257)

```

**Comment by tinevez** [comment]
I could pinpoint the error to the 
```java
ArrayJ.fillMemory()
```
method, which does not work.

If in the test file `TestAbsolute` you replace at line 20 
```java
in.fillMemory(-1);
```
by
```java
in.writeFromArray( new int[] { -1, -1, -1, -1 } );
```
then the test pass.

Any other change (using UINT, INT, FLOAT etc.) has no impact.

**Comment by StRigaud** [comment]
Indeed, the memory fill process is different for MacOS (I forgot about this). I will try to dig this
